spring.application.name=Ticketline
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketline
spring.datasource.username=postgres
spring.datasource.password=12345

#(o motor por trás do Spring Data JPA) que verifica a base de dados. Se a tabela não existir, ele cria-a.
spring.jpa.hibernate.ddl-auto=update

